// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpxYR4-bFWp3RMCAimj4CPKScrlStIvpk',
    appId: '1:762545270724:web:7fddbfbabd35b35976fe91',
    messagingSenderId: '762545270724',
    projectId: 'resep-makanan-34ca1',
    authDomain: 'resep-makanan-34ca1.firebaseapp.com',
    storageBucket: 'resep-makanan-34ca1.appspot.com',
    measurementId: 'G-CLJFDN9K00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlIk45MvRNsv90VDofECtkiUdDVl9aM8A',
    appId: '1:762545270724:android:570af03681f51faa76fe91',
    messagingSenderId: '762545270724',
    projectId: 'resep-makanan-34ca1',
    storageBucket: 'resep-makanan-34ca1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_n9Co2XZjRni56G3Cl1boxTtRD6VqB4E',
    appId: '1:762545270724:ios:56aff22b17353f7f76fe91',
    messagingSenderId: '762545270724',
    projectId: 'resep-makanan-34ca1',
    storageBucket: 'resep-makanan-34ca1.appspot.com',
    iosBundleId: 'com.example.resepMakanan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpxYR4-bFWp3RMCAimj4CPKScrlStIvpk',
    appId: '1:762545270724:web:7863470e3f9c082f76fe91',
    messagingSenderId: '762545270724',
    projectId: 'resep-makanan-34ca1',
    authDomain: 'resep-makanan-34ca1.firebaseapp.com',
    storageBucket: 'resep-makanan-34ca1.appspot.com',
    measurementId: 'G-Y8WXYVZF1N',
  );
}
